name: JsonAutomated
on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1-pyver: ${{ steps.read-pyversion.outputs.pyver }}
    steps:
      - uses: actions/checkout@v3
      - name: Read Python versions from file
        id: read-pyversion
        run: |        
          echo ::set-output name=pyver::$(cat ./info.json)
      - name: Print Pyver Output
        run: |
          echo "ver ${{ steps.read-pyversion.outputs.pyver }}"
    
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ${{fromJson(needs.job1.outputs.job1-pyver)}}
    steps:
      - run: echo "Python version"
